# Generated by Django 2.2.4 on 2019-08-13 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 13, 19, 28, 6, 449049)),
        ),
        migrations.AlterField(
            model_name='message',
            name='time_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 13, 19, 28, 6, 452383)),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 13, 19, 28, 6, 448482)),
        ),
    ]
