# Generated by Django 2.2.4 on 2019-08-12 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devbook', '0002_auto_20190812_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 12, 21, 41, 38, 818540)),
        ),
        migrations.AlterField(
            model_name='message',
            name='time_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 12, 21, 41, 38, 821304)),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 12, 21, 41, 38, 818068)),
        ),
    ]
