# Generated by Django 2.2.4 on 2019-08-08 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devbook', '0003_auto_20190808_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 8, 17, 20, 30, 975738)),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 8, 17, 20, 30, 975329)),
        ),
    ]
