# Generated by Django 2.2.4 on 2019-08-13 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devbook', '0004_auto_20190813_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 13, 17, 58, 40, 684808)),
        ),
        migrations.AlterField(
            model_name='message',
            name='time_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 13, 17, 58, 40, 687557)),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 13, 17, 58, 40, 684337)),
        ),
    ]
