# Generated by Django 2.2.4 on 2019-08-09 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devbook', '0012_auto_20190808_2233'),
        ('devbook', '0009_auto_20190808_2208'),
    ]

    operations = [
    ]
